version: "3.9"
services:
  backend:
    build:
      context: ./openperplex_backend_os
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./openperplex_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

