version: "3.9"

services:
  backend:
    build:
      context: ./openperplex_backend_os
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    expose:
      - "4000" # Allows other services in the same network to communicate
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4000"]

  frontend:
    build:
      context: ./openperplex_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["npm", "run", "dev"]
