version: "3.9"

services:
  backend:
    build:
      context: ./openperplex_backend_os
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./openperplex_backend_os/.env
    expose:
      - "4000"

  frontend:
    build:
      context: ./openperplex_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:4000  # Pass API URL to frontend
